#include "libcpu.h"
/*****************************************************************************/
uint32_t	UniqueId[3];//处理器序列号 
/*****************************************************************************/
void softDelayMs(uint32_t ms){// 同样使用易变变量防止外层循环被优化
	volatile uint32_t ms_count = ms;
	for(; ms_count > 0; ms_count--){
		softDelayUs(1000);
	}
}

void softDelayUs(uint32_t us){
	// 粗略估算：1us 大约需要 hclk_mhz 个周期
	// 这里的 0.9 是经验修正系数，用于补偿 Flash 预取和流水线带来的加速效应
	// 具体系数需根据实际示波器测量调整
	uint32_t loops = us * 168; 
	// 使用 volatile 防止优化
	volatile uint32_t count = loops;
	while(count--){
			__NOP(); // 插入空指令，强制消耗时钟周期
			__NOP(); // 可以多加几个来增加精度
	}
}





uint16_t cpuGetFlashSize(void){//获取处理器程序容量
   return *(volatile uint16_t*)(0x1FFF7A22);
}

void readStm32UniqueID(void){//获取处理器唯一序列号        
    UniqueId[0] = *(volatile uint32_t*)(0x1FFF7A10);
    UniqueId[1] = *(volatile uint32_t*)(0x1FFF7A14);
    UniqueId[2] = *(volatile uint32_t*)(0x1FFF7A18);
}

void UsbGpioReset(void){//模拟USB拔插动作并关闭VBUS供电
	GPIO_InitTypeDef GPIO_InitStruct;
	/* GPIO Ports Clock Enable */
	__HAL_RCC_GPIOA_CLK_ENABLE();
	/*Configure GPIO pin Output Level */
	HAL_GPIO_WritePin(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin, GPIO_PIN_RESET);
	/*Configure GPIO pin : PA12 */
	GPIO_InitStruct.Pin = USB_OTG_FS_DP_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLDOWN;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(USB_OTG_FS_DP_GPIO_Port, &GPIO_InitStruct);
	HAL_GPIO_WritePin(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin, GPIO_PIN_RESET);                                            
	softDelayMs(1);
	//先把PA12拉低再拉高，利用D+模拟USB的拔插动作   
	HAL_GPIO_WritePin(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin, GPIO_PIN_SET);
	softDelayMs(1);
	HAL_GPIO_DeInit(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin);
	__HAL_RCC_GPIOA_CLK_DISABLE();
	__HAL_RCC_GPIOG_CLK_ENABLE();
	//关闭USB供电
#if defined(LDR2P1_G5_A1_20250731_DUAL) || defined(LDR2P1_G5_A1_20250731_TRIP)
	GPIO_InitStruct.Pin = USB_FS_PSON_LEGACY_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLDOWN;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(USB_FS_PSON_LEGACY_GPIO_Port, &GPIO_InitStruct);
	SET_USB_FS_PSON_LEGACY_OFF;
#endif
#if defined (LDR2P1_G5_A1_20250910_DUAL) || defined(LDR2P1_G5_A1_20250910_TRIP)
	GPIO_InitStruct.Pin = USBA0_PSON_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLDOWN;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(USBA0_PSON_GPIO_Port, &GPIO_InitStruct);
	SET_USBA0_PSON_OFF;
#endif
	softDelayMs(10);
#if defined(LDR2P1_G5_A1_20250731_DUAL) || defined(LDR2P1_G5_A1_20250731_TRIP)
	HAL_GPIO_DeInit(USB_FS_PSON_LEGACY_GPIO_Port, USB_FS_PSON_LEGACY_Pin);
#endif
#if defined (LDR2P1_G5_A1_20250910_DUAL) || defined(LDR2P1_G5_A1_20250910_TRIP)
	HAL_GPIO_DeInit(USBA0_PSON_GPIO_Port, USBA0_PSON_Pin);
#endif
	__HAL_RCC_GPIOG_CLK_DISABLE();	
	__HAL_RCC_USB_OTG_FS_CLK_DISABLE();//关闭USB时钟
	HAL_NVIC_DisableIRQ(OTG_FS_IRQn);//关闭USB 中断
	HAL_NVIC_ClearPendingIRQ(OTG_FS_IRQn);//清楚 USB 中断标志
}

void SystemClock_Reset(void){//复位系统时钟
	RCC_OscInitTypeDef RCC_OscInitStruct = {0};
	RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
	__HAL_RCC_BACKUPRESET_RELEASE();
	__HAL_RCC_BACKUPRESET_FORCE();
	__HAL_RCC_PLL_DISABLE();
	__HAL_RCC_HSI_DISABLE();
	/** Configure the main internal regulator output voltage */
	__HAL_RCC_PWR_CLK_DISABLE();
	__HAL_RCC_PWR_CLK_ENABLE();
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
	/** Initializes the CPU, AHB and APB busses clocks */
	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
	RCC_OscInitStruct.HSIState = RCC_HSI_ON;
	RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
	if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK){
		Error_Handler();
	}
	/** Initializes the CPU, AHB and APB busses clocks */
	RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
	RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
	RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
	RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
	if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK){
		Error_Handler();
	}
}
void resetInit(void){//复位后初始化
	HAL_DeInit();
	//复位RCC时钟
	SystemClock_Reset();
	UsbGpioReset();
	__enable_irq();
}


uint32_t getOriginBootloadCrc(void){//计算MCU Bootload CRC32
	uint8_t val;
	uint32_t i;
	uint32_t crc32;
	crc32Clear();
	for(i = BOOTLOADER_FLASH_START_ADDRESS;i < BOOTLOADER_FLASH_END_ADDRESS;i ++){
		val = *(__IO uint8_t*)(i);
		crc32 = crc32CalculateAdd(val);//CRC32计算连续字节
	}
	return crc32;	
}
uint32_t getOriginAppCrc(void){//计算MCU APP CRC32
	uint8_t val;
	uint32_t i;
	uint32_t crc32;
	crc32Clear();
	for(i = APPLICATION_FLASH_START_ADDRESS;i < APPLICATION_FLASH_END_ADDRESS;i ++){
		val = *(__IO uint8_t*)(i);
		crc32 = crc32CalculateAdd(val);//CRC32计算连续字节
	}
	return crc32;	
}

void morseCodeDiag(uint8_t diag){//蜂鸣器诊断声音 摩尔斯电码
	//关闭USB VBUS
	switch(diag){
		case '0':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case '1':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		};
		case '2':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		};
		case '3':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case '4':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case '5':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '6':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '7':{	
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '8':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '9':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'A':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'B':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;			
		}
		case 'C':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'D':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'E':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'F':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'G':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'H':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;			
		}
		case 'I':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'J':{
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'K':{
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'L':{//．━ ．．
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		//
		case 'M':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'N':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'O':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'P':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'Q':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'R':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'S':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'T':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'U':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'V':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'W':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'X':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'Y':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'Z':{//━ ━
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;softDelayMs(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;softDelayMs(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		default:break;
	}
	softDelayMs(3000);
}

