#ifndef __DCHMIRES_H__
#define __DCHMIRES_H__
/*****************************************************************************/
#define HMI_BLACK     																	0x0000//黑色    
#define HMI_NAVY      																	0x000F//深蓝色  
#define HMI_DGREEN    																	0x03E0//深绿色  
#define HMI_DCYAN     																	0x03EF//深青色  
#define HMI_MAROON    																	0x7800//深红色      
#define HMI_PURPLE    																	0x780F//紫色  
#define HMI_OLIVE     																	0x7BE0//橄榄绿      
#define HMI_LGRAY     																	0xC618//灰白色
#define HMI_DGRAY     																	0x7BEF//深灰色      
#define HMI_BLUE      																	0x001F//蓝色    
#define HMI_GREEN     																	0x07E0//绿色          
#define HMI_CYAN      																	0x07FF//青色  
#define HMI_RED       																	0xF800//红色       
#define HMI_MAGENTA   																	0xF81F//品红    
#define HMI_YELLOW    																	0xFFE0//黄色        
#define HMI_WHITE     																	0xFFFF//白色  
/*****************************************************************************/
//HMI页面编号
#define GDDC_PAGE_START																	0
#define GDDC_PAGE_POWERUP_1470													1
#define GDDC_PAGE_POWERUP_TRI														2
#define GDDC_PAGE_POWERUP_1940													3
#define GDDC_PAGE_POWERUP_450														4
#define GDDC_PAGE_PASSCODE															5
#define GDDC_PAGE_NEW_PASSCODE													6
#define GDDC_PAGE_STANDBY_DUAL													7
#define GDDC_PAGE_STANDBY_TRI														8
#define GDDC_PAGE_READY																	9
#define GDDC_PAGE_OPTION																10//选项页面
#define GDDC_PAGE_SCHEME_CLASSIFY_TRI										11//方案分类页 三波长
#define GDDC_PAGE_SCHEME_CLASSIFY_DUAL									12//方案分类页 双波长
#define GDDC_PAGE_SCHEME_DETAIL													13//方案分类页 自定义
#define GDDC_PAGE_INFORMATION														14//信息页面
#define GDDC_PAGE_DIAGNOSIS															15//诊断页面
#define GDDC_PAGE_DIAGNOSIS_RAW													16//诊断页面-原始寄存器
#define GDDC_PAGE_RENAME																17//SCHEME更名
#define GDDC_PAGE_RESTORE																18//弹出菜单 确认恢复默认值
#define GDDC_PAGE_WEAR_SAFETY														19//脚踏安全警告
//GDDC页面控件编号
#define GDDC_PAGE_PASSCODE_KEY_NUM1											1
#define GDDC_PAGE_PASSCODE_KEY_NUM2											2
#define GDDC_PAGE_PASSCODE_KEY_NUM3											3
#define GDDC_PAGE_PASSCODE_KEY_NUM4											4
#define GDDC_PAGE_PASSCODE_KEY_NUM5											5
#define GDDC_PAGE_PASSCODE_KEY_NUM6											6
#define GDDC_PAGE_PASSCODE_KEY_NUM7											7
#define GDDC_PAGE_PASSCODE_KEY_NUM8											8
#define GDDC_PAGE_PASSCODE_KEY_NUM9											9
#define GDDC_PAGE_PASSCODE_KEY_NUM0											10
#define GDDC_PAGE_PASSCODE_KEY_CANCEL										11
#define GDDC_PAGE_PASSCODE_KEY_BACKSPACE								12
#define GDDC_PAGE_PASSCODE_KEY_CHANGEPASSCODE						13
#define GDDC_PAGE_PASSCODE_KEY_ENTER										14
#define GDDC_PAGE_PASSCODE_TEXTDISPLAY									15
/*****************************************************************************/
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM1									1
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM2									2
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM3									3
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM4									4
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM5									5
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM6									6
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM7									7
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM8									8
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM9									9
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM0									10
#define GDDC_PAGE_NEWPASSCODE_KEY_CANCEL								11
#define GDDC_PAGE_NEWPASSCODE_KEY_BACKSPACE							12
#define GDDC_PAGE_NEWPASSCODE_KEY_SAVE									13
#define GDDC_PAGE_NEWPASSCODE_KEY_BACK									14
#define GDDC_PAGE_NEWPASSCODE_TEXTDISPLAY								15
/*****************************************************************************/
#define GDDC_PAGE_STANDBY_KEY_POWER_SEL_ADD							1//当前选择功率增加
#define GDDC_PAGE_STANDBY_KEY_POWER_SEL_INC							2//当前选择功率减小
#define GDDC_PAGE_STANDBY_KEY_POWER_CH0_ADD							3//功率增加
#define GDDC_PAGE_STANDBY_KEY_POWER_CH0_INC							4//功率减小
#define GDDC_PAGE_STANDBY_KEY_POWER_CH1_ADD             5
#define GDDC_PAGE_STANDBY_KEY_POWER_CH1_INC             6
#define GDDC_PAGE_STANDBY_KEY_POWER_RED_ADD             7
#define GDDC_PAGE_STANDBY_KEY_POWER_RED_INC             8
#define GDDC_PAGE_STANDBY_KEY_POWER_AIM_ADD							9//指示光亮度加
#define GDDC_PAGE_STANDBY_KEY_POWER_AIM_INC							10//指示光亮度减
#define GDDC_PAGE_STANDBY_KEY_STANDBY										11//进入准备
#define GDDC_PAGE_STANDBY_KEY_MODE_CW										12//连续模式
#define	GDDC_PAGE_STANDBY_KEY_MODE_MP										13//脉冲模式
#define GDDC_PAGE_STANDBY_KEY_ENTER_OPTION							14//
#define GDDC_PAGE_STANDBY_KEY_ENTER_SCHEME							15//
#define GDDC_PAGE_STANDBY_KEY_SCHEME_SAVE								16//
#define GDDC_PAGE_STANDBY_KEY_SCHEME_NEXT								17//
#define GDDC_PAGE_STANDBY_KEY_SCHEME_LAST								18//
#define GDDC_PAGE_STANDBY_KEY_POSWIDTH_ADD							19//	
#define GDDC_PAGE_STANDBY_KEY_POSWIDTH_INC							20//
#define GDDC_PAGE_STANDBY_KEY_NEGWIDTH_ADD							21//
#define GDDC_PAGE_STANDBY_KEY_NEGWIDTH_INC							22//
#define GDDC_PAGE_STANDBY_KEY_SELECT_CH0A								23//1470
#define GDDC_PAGE_STANDBY_KEY_SELECT_CH0B								45//1940
#define GDDC_PAGE_STANDBY_KEY_SELECT_CH0C								46//450
#define GDDC_PAGE_STANDBY_KEY_SELECT_CH1A								24//980
#define GDDC_PAGE_STANDBY_KEY_SELECT_CH1B								47//蓝光980			
#define GDDC_PAGE_STANDBY_KEY_SELECT_RED								25
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_NAME							26//方案名称显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_SET_POWER_SEL			27//当前设定功率
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_SET_POWER_CH0			28//设定功率 1470 / 1940
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_SET_POWER_CH1     29//设定功率 980
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_SET_POWER_RED     30//设定功率 635(工作激光)
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_SET_POWER_AIM     31//设定功率 650(指示激光)
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_WARN							32//报警显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_AVERAGE_POWER			33//平均功率显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_FREQUENCY					34//频率显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_DUTYCYCLE					35//占空比显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_POSWIDTH					36//正脉宽显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_NEGWIDTH					37//负脉宽显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_TOTAL_POWER				38//总功率显示
#define GDDC_PAGE_STANDBY_PROGRESS_SET_POWER_SEL				39//当前功率设定拖动条
#define GDDC_PAGE_STANDBY_PROGRESS_SET_POWER_CH0			  40//功率设定拖动条 1470 /1940
#define GDDC_PAGE_STANDBY_PROGRESS_SET_POWER_CH1        41//功率设定拖动条 980
#define GDDC_PAGE_STANDBY_PROGRESS_SET_POWER_RED 				42//功率设定拖动条 635(工作激光)
#define GDDC_PAGE_STANDBY_PROGRESS_SET_POWER_AIM				43//功率设定拖动条 650(指示激光)
#define GDDC_PAGE_STANDBY_ICON_MPKEY										44//脉冲模式背景图
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_DEBUG							99//显示调试信息
/*****************************************************************************/
#define GDDC_PAGE_READY_TEXTDISPLAY_NAME								1//方案名称显示
#define GDDC_PAGE_READY_TEXTDISPLAY_POWER_CH0						2//发射功率显示 1470 /1940
#define GDDC_PAGE_READY_TEXTDISPLAY_POWER_CH1           3//发射功率显示 980
#define GDDC_PAGE_READY_TEXTDISPLAY_POWER_RED           4//发射功率显示 635
#define GDDC_PAGE_READY_TEXTDISPLAY_POWER_AIM						5//发射功率显示 650
#define GDDC_PAGE_READY_TEXTDISPLAY_POWER_TOTAL					6//总发射功率显示
#define GDDC_PAGE_READY_TEXTDISPLAY_ENERGEY							7//发射能量显示
#define GDDC_PAGE_READY_TEXTDISPLAY_TREATMENT_TIME			8//发射时间显示
#define GDDC_PAGE_READY_TEXTDISPLAY_ACOUSTIC_ENERGEY		9//提示音能量
#define GDDC_PAGE_READY_TEXTDISPLAY_ACOUSTIC_TIME				10//提示音时间
#define GDDC_PAGE_READY_TEXTDISPLAY_ACOUSTIC_CYCLE			11//提示音周期
#define GDDC_PAGE_READY_TEXTDISPLAY_SHOW_WAVE						12//选择波长显示
#define GDDC_PAGE_READY_KEY_ACOUSTIC_ENERGY_ADD					13//提示音能量增加
#define GDDC_PAGE_READY_KEY_ACOUSTIC_ENERGY_INC					14//提示音能量减小
#define GDDC_PAGE_READY_KEY_ACOUSTIC_TIME_ADD						15//提示音时间增加
#define GDDC_PAGE_READY_KEY_ACOUSTIC_TIME_INC						16//提示音时间减小
#define GDDC_PAGE_READY_KEY_READY												17//切换待机按键
#define GDDC_PAGE_READY_TEXTDISPLAY_DEBUG								99//显示调试信息
/*****************************************************************************/
#define GDDC_PAGE_OPTION_KEY_TONE									 			1//蜂鸣器声光同步												
#define GDDC_PAGE_OPTION_KEY_BEEM_VOLUME_ADD						2//蜂鸣器音量加
#define GDDC_PAGE_OPTION_KEY_BEEM_VOLUME_INC						3//蜂鸣器音量减
#define GDDC_PAGE_OPTION_KEY_LCD_BRG_ADD								4//液晶屏亮度增加
#define GDDC_PAGE_OPTION_KEY_LCD_BRG_INC								5//液晶屏亮度减少
#define GDDC_PAGE_OPTION_KEY_ENTER_OK										6//返回待机页面
#define GDDC_PAGE_OPTION_KEY_ENTER_INFORMATION					7//进入信息菜单
#define GDDC_PAGE_OPTION_KEY_HAND_SWITCH_ON							8//
#define GDDC_PAGE_OPTION_KEY_ENTER_ENGINEER							9//进入工程师模式。
#define GDDC_PAGE_OPTION_TEXTDISPLAY_BEEM_VOLUME				10
#define GDDC_PAGE_OPTION_TEXTDISPLAY_LCD_BRG						11
#define GDDC_PAGE_OPTION_PROGRESS_BEEM_VOLUME						12//蜂鸣器音量调节
#define GDDC_PAGE_OPTION_PROGRESS_LCD_BRG								13//屏幕亮度调节
#define GDDC_PAGE_OPTION_KEY_RESTORE										14//恢复默认设置
/*****************************************************************************/
#define GDDC_PAGE_RESTORE_KEY_CANCEL										1//取消恢复默认值
#define GDDC_PAGE_RESTORE_KEY_YES												2//确认恢复默认值
/*****************************************************************************/
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_PHLEBOLOGY				1		
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_PROCTOLOGY				2
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_GTNECOLOGY				3	
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_ENT								4
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_NEUROSURGERY			5
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_DERAMATOLOGY			6
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_LIPOSUCTION				7
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_DENTISTRY					8
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_THERAPY						9
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_CUSTOM						10
#define GDDC_PAGE_SCHMEM_CLASSIFY_KEY_RETURN						11
/*****************************************************************************/
//方案页面
#define GDDC_PAGE_SCHEME_KEY_RENAME											1//更名按键
#define GDDC_PAGE_SCHEME_KEY_OK													2//确定
#define GDDC_PAGE_SCHEME_KEY_CANCEL											3//取消
#define GDDC_PAGE_SCHEME_KEY_SELECT_0										4	
#define GDDC_PAGE_SCHEME_KEY_SELECT_1										5
#define GDDC_PAGE_SCHEME_KEY_SELECT_2										6
#define GDDC_PAGE_SCHEME_KEY_SELECT_3										7
#define GDDC_PAGE_SCHEME_KEY_SELECT_4										8
#define GDDC_PAGE_SCHEME_KEY_SELECT_5										9
#define GDDC_PAGE_SCHEME_KEY_SELECT_6										10
#define GDDC_PAGE_SCHEME_KEY_SELECT_7										11
#define GDDC_PAGE_SCHEME_KEY_SELECT_8										12
#define GDDC_PAGE_SCHEME_KEY_SELECT_9										13
#define GDDC_PAGE_SCHEME_KEY_SELECT_10									14
#define GDDC_PAGE_SCHEME_KEY_SELECT_11									15
#define GDDC_PAGE_SCHEME_KEY_SELECT_12									16
#define GDDC_PAGE_SCHEME_KEY_SELECT_13									17
#define GDDC_PAGE_SCHEME_KEY_SELECT_14									18
#define GDDC_PAGE_SCHEME_KEY_SELECT_15									19
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_0						20
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_1						21
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_2						22
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_3						23
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_4						24
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_5						25
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_6						26
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_7						27
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_8						28
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_9						29
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_10					30
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_11					31
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_12					32
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_13					33
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_14					34
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_15					35
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_DETAIL0						36
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_DETAIL1						37
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_CLASSIFY						38
#define GDDC_PAGE_SCHEME_KEY_LAST_PAGE									39
#define GDDC_PAGE_SCHEME_KEY_NEXT_PAGE									40
/*****************************************************************************/
#define GDDC_PAGE_INFO_KEY_ENTER_OK											1
#define GDDC_PAGE_INFO_TEXTDISPLAY_TPYE									2
#define GDDC_PAGE_INFO_TEXTDISPLAY_SN										3
#define GDDC_PAGE_INFO_TEXTDISPLAY_LASER_WAVELENGTH			4
#define GDDC_PAGE_INFO_TEXTDISPLAY_MAX_LASER_POWER			5
#define GDDC_PAGE_INFO_TEXTDISPLAY_HARDWAR_VERSIONE			6
#define GDDC_PAGE_INFO_TEXTDISPLAY_SOFTWARE_VERSION			7
#define GDDC_PAGE_INFO_TEXTDISPLAY_MANUFACTURE_DATE			8
#define GDDC_PAGE_INFO_TEXTDISPLAY_UUID									9
/*****************************************************************************/
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO0						1
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO1						2
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO2						3
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO3						4
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO4						17
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO5						22
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO6						23
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO7						24
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO8						25
//通道0 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P1				100
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P2				101
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P3				102
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P4				103
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P5				104
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P6				105
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P7				106
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P8				107
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P9				108
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_1P0				109
//通道1 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P1				110
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P2				111
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P3				112
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P4				113
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P5				114
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P6				115
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P7				116
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P8				117
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P9				118
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_1P0				119
//通道2 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P1				120
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P2				121
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P3				122
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P4				123
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P5				124
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P6				125
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P7				126
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P8				127
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P9				128
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_1P0				129
//通道3 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P1				130
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P2				131
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P3				132
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P4				133
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P5				134
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P6				135
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P7				136
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P8				137
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P9				138
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_1P0				139
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_YEAR						140
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_MONTH						141
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_DAY							142
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_SN							143
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_RED_LED_DC			144
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_GREEN_LED_DC		145
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_BLUE_LED_DC			146
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_FIRMWARE_INFO		147
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_SET_AIM_GAIN		148
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_FIBER_DETECT  	149
//
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_TEMPERATURE			300//屏蔽温度检测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_FIBER_PROBE			301//屏蔽光纤探测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_RFID						302//屏蔽RFID
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_ESTOP						303//屏蔽急停检测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_FOOTSWITCH			304//屏蔽脚踏检测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_INTERLOCK				305//屏蔽安全连锁
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_FAN_CONTRAL			306//屏蔽风扇
#define GDDC_PAGE_DISGNOSIS_KEY_CALIBRATION_MODE				307//切换正常和校正模式
#define GDDC_PAGE_DISGNOSIS_KEY_SAVE_EPROM							308//储存参数到 ERPOM 
#define GDDC_PAGE_DISGNOSIS_KEY_CLEAR_EPROM							309//恢复默认参数 EPROM						
#define GDDC_PAGE_DISGNOSIS_KEY_CLEAR_CRC								310//清除固件CRC信息
#define GDDC_PAGE_DISGNOSIS_KEY_UPDATE_BOOTLOAD_REQ			311//更新引导固件请求
#define GDDC_PAGE_DISGNOSIS_KEY_UPDATE_BOOTLOAD_YES			312//确认更新固件
#define GDDC_PAGE_DISGNOSIS_KEY_UPDATE_BOOTLOAD_NO			313//确认不更新固件
#define GDDC_PAGE_DISGNOSIS_KEY_OPEN_ILOCK							314//默认常开安全连锁
#define GDDC_PAGE_DISGNOSIS_KEY_RAW_DATE								315//进去RAW数据信息
#define GDDC_PAGE_DIAGNOSIS_KEY_ENTER_OK								99
/*****************************************************************************/
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO0						1
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO1						2
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO2						3
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO3						4
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO4						5
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO5						6
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO6						7
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO7						8
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO8						9
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO9						10
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO10					11
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO11					12
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO12					13
#define GDDC_PAGE_DIAGNOSIS_RAW_TEXTDISPLAY_INFO13					14
#define GDDC_PAGE_DIAGNOSIS_RAW_KEY_ENTER_OK								99
/*****************************************************************************/
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH0				10
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH1				11
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH2				12
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH3				13
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH4				14
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH5				15
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH6				16
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CSET_CH7				17

#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH0			20
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH1			21
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH2			22
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH3			23
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH4			24
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH5			25
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH6			26
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CDISP_CH7			27

#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_DIODE_TEMP			30
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_HWATER_TEMP		31
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_CWATER_TEMP		32
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_PID0						33
#define GDDC_PAGE_DIAGNOSIS_CALI_TEXTDISPLAY_PID1						34

#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH0						40
#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH1						41
#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH2						42
#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH3						43
#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH4						44
#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH5						45
#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH6						46
#define GDDC_PAGE_DIAGNOSIS_CALI_BUTTON_LASON_CH7						47
	
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P5						50
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P10						51
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P15						52
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P20						53
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P25						54
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P30						55
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P35						56
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P40						57
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P45						58
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P50						59
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P55						60
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P60						61
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P65						62
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P70						63
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P75						64
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P80						65
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P85						66
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P90						67
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P95						68
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_0P100					69

#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P5						70
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P10						71
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P15						72
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P20						73
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P25						74
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P30						75
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P35						76
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P40						77
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P45						78
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P50						79
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P55						80
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P60						81
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P65						82
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P70						83
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P75						84
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P80						85
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P85						86
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P90						87
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P95						88
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_1P100					89

#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P5						90
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P10						91
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P15						92
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P20						93
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P25						94
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P30						95
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P35						96
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P40						97
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P45						98
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P50						99
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P55						100
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P60						101
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P65						102
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P70						103
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P75						104
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P80						105
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P85						106
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P90						107
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P95						108
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_2P100					109

#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P5						110
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P10						111
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P15						112
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P20						113
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P25						114
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P30						115
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P35						116
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P40						117
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P45						118
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P50						119
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P55						120
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P60						121
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P65						122
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P70						123
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P75						124
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P80						125
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P85						126
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P90						127
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P95						128
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_3P100					129

#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P5
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P10
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P15
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P20
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P25
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P30
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P35
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P40
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P45
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P50
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P55
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P60
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P65
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P70
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P75
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P80
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P85
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P90
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P95
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_4P100

#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P5
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P10
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P15
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P20
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P25
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P30
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P35
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P40
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P45
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P50
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P55
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P60
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P65
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P70
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P75
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P80
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P85
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P90
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P95
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_5P100

#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P5
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P10
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P15
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P20
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P25
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P30
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P35
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P40
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P45
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P50
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P55
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P60
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P65
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P70
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P75
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P80
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P85
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P90
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P95
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_6P100

#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P5
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P10
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P15
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P20
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P25
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P30
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P35
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P40
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P45
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P50
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P55
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P60
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P65
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P70
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P75
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P80
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P85
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P90
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P95
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_CALI_7P100

#define GDDC_PAGE_DIAGNOSIS_CALI_KEY_ENTER_OK
/*****************************************************************************/
#define GDDC_PAGE_RENAME_TEXTDISPLAY_NEWNAME						1
#define GDDC_PAGE_RENAME_KEY_ENTER											2
#define GDDC_PAGE_RENAME_KEY_EXIT												3
/*****************************************************************************/
#endif



