#ifndef __DCHMIRES_H__
#define __DCHMIRES_H__
/*****************************************************************************/
#define HMI_BLACK     																	0x0000//黑色    
#define HMI_NAVY      																	0x000F//深蓝色  
#define HMI_DGREEN    																	0x03E0//深绿色  
#define HMI_DCYAN     																	0x03EF//深青色  
#define HMI_MAROON    																	0x7800//深红色      
#define HMI_PURPLE    																	0x780F//紫色  
#define HMI_OLIVE     																	0x7BE0//橄榄绿      
#define HMI_LGRAY     																	0xC618//灰白色
#define HMI_DGRAY     																	0x7BEF//深灰色      
#define HMI_BLUE      																	0x001F//蓝色    
#define HMI_GREEN     																	0x07E0//绿色          
#define HMI_CYAN      																	0x07FF//青色  
#define HMI_RED       																	0xF800//红色       
#define HMI_MAGENTA   																	0xF81F//品红    
#define HMI_YELLOW    																	0xFFE0//黄色        
#define HMI_WHITE     																	0xFFFF//白色  
/*****************************************************************************/
//HMI页面编号
#define GDDC_PAGE_POWERUP																0
#define GDDC_PAGE_PASSCODE															1
#define GDDC_PAGE_NEW_PASSCODE													2
#define GDDC_PAGE_STANDBY_CW														3
#define GDDC_PAGE_STANDBY_SP														4
#define GDDC_PAGE_STANDBY_MP														5
#define GDDC_PAGE_READY																	6
#define GDDC_PAGE_OPTION																7//选项页面
#define GDDC_PAGE_SCHEME_0															8//方案页面第一页
#define GDDC_PAGE_SCHEME_1															9//方案页面第二页
#define GDDC_PAGE_INFORMATION														10//信息页面
#define GDDC_PAGE_DIAGNOSIS															11//诊断页面
#define GDDC_PAGE_RENAME																12//SCHEME更名
//GDDC页面控件编号
#define GDDC_PAGE_PASSCODE_KEY_NUM1											1
#define GDDC_PAGE_PASSCODE_KEY_NUM2											2
#define GDDC_PAGE_PASSCODE_KEY_NUM3											3
#define GDDC_PAGE_PASSCODE_KEY_NUM4											4
#define GDDC_PAGE_PASSCODE_KEY_NUM5											5
#define GDDC_PAGE_PASSCODE_KEY_NUM6											6
#define GDDC_PAGE_PASSCODE_KEY_NUM7											7
#define GDDC_PAGE_PASSCODE_KEY_NUM8											8
#define GDDC_PAGE_PASSCODE_KEY_NUM9											9
#define GDDC_PAGE_PASSCODE_KEY_NUM0											10
#define GDDC_PAGE_PASSCODE_KEY_CANCEL										11
#define GDDC_PAGE_PASSCODE_KEY_BACKSPACE								12
#define GDDC_PAGE_PASSCODE_KEY_CHANGEPASSCODE						13
#define GDDC_PAGE_PASSCODE_KEY_ENTER										14
#define GDDC_PAGE_PASSCODE_TEXTDISPLAY									15
/*****************************************************************************/
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM1									1
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM2									2
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM3									3
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM4									4
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM5									5
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM6									6
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM7									7
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM8									8
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM9									9
#define GDDC_PAGE_NEWPASSCODE_KEY_NUM0									10
#define GDDC_PAGE_NEWPASSCODE_KEY_CANCEL								11
#define GDDC_PAGE_NEWPASSCODE_KEY_BACKSPACE							12
#define GDDC_PAGE_NEWPASSCODE_KEY_SAVE									13
#define GDDC_PAGE_NEWPASSCODE_KEY_BACK									14
#define GDDC_PAGE_NEWPASSCODE_TEXTDISPLAY								15
/*****************************************************************************/
#define GDDC_PAGE_STANDBY_KEY_POWER_ADD									1//功率增加
#define GDDC_PAGE_STANDBY_KEY_POWER_DEC									2//功率减小
#define GDDC_PAGE_STANDBY_KEY_STANDBY										3//进入准备
#define GDDC_PAGE_STANDBY_KEY_MODE_CW										4//连续模式
#define GDDC_PAGE_STANDBY_KEY_MODE_SP										5
#define	GDDC_PAGE_STANDBY_KEY_MODE_MP										6//连续模式
#define GDDC_PAGE_STANDBY_KEY_ENTER_OPTION							7//脉冲模式
#define GDDC_PAGE_STANDBY_KEY_ENTER_SCHEME							8//
#define GDDC_PAGE_STANDBY_KEY_SCHEME_SAVE								9//
#define GDDC_PAGE_STANDBY_KEY_SCHEME_NEXT								10//
#define GDDC_PAGE_STANDBY_KEY_SCHEME_LAST								11//
#define GDDC_PAGE_STANDBY_KEY_AIM_BRG_ADD								12//指示光亮度加
#define GDDC_PAGE_STANDBY_KEY_AIM_BRG_DEC								13//指示光亮度减
#define GDDC_PAGE_STANDBY_KEY_POSWIDTH_ADD							14//	
#define GDDC_PAGE_STANDBY_KEY_POSWIDTH_DEC							15//
#define GDDC_PAGE_STANDBY_KEY_NEGWIDTH_ADD							16//
#define GDDC_PAGE_STANDBY_KEY_NEGWIDTH_DEC							17//
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_NAME							18//方案名称显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_SET_POWER					19//设定功率显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_WARN							20//报警显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_AIM_BRG						21//指示光亮度显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_AVERAGE_POWER			22//平均功率显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_FREQUENCY					23//频率显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_DUTYCYCLE					24//占空比显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_POSWIDTH					25//正脉宽显示
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_NEGWIDTH					26//负脉宽显示
#define GDDC_PAGE_STANDBY_PROGRESS_SET_POWER						27//功率设定拖动条
#define GDDC_PAGC_STANDBY_PROGRESS_AIM_BRG							28
#define GDDC_PAGE_STANDBY_TEXTDISPLAY_DEBUG							99//显示调试信息
/*****************************************************************************/
#define GDDC_PAGE_READY_TEXTDISPLAY_NAME								1//方案名称显示
#define GDDC_PAGE_READY_TEXTDISPLAY_POWER								2//发射功率显示
#define GDDC_PAGE_READY_TEXTDISPLAY_ENERGEY							3//发射能量显示
#define GDDC_PAGE_READY_TEXTDISPLAY_TREATMENT_TIME			4//发射时间显示
#define GDDC_PAGE_READY_TEXTDISPLAY_ACOUSTIC_ENERGEY		5//提示音能量
#define GDDC_PAGE_READY_TEXTDISPLAY_ACOUSTIC_TIME				6//提示音时间
#define GDDC_PAGE_READY_TEXTDISPLAY_ACOUSTIC_CYCLE			7//提示音周期
#define GDDC_PAGE_READY_KEY_ACOUSTIC_ENERGY_ADD					8//提示音能量增加
#define GDDC_PAGE_READY_KEY_ACOUSTIC_ENERGY_DEC					9//提示音能量减小
#define GDDC_PAGE_READY_KEY_ACOUSTIC_TIME_ADD						10//提示音时间增加
#define GDDC_PAGE_READY_KEY_ACOUSTIC_TIME_DEC						11//提示音时间减小
#define GDDC_PAGE_READY_KEY_READY												12//切换待机按键
#define GDDC_PAGE_READY_TEXTDISPLAY_DEBUG								99//显示调试信息
/*****************************************************************************/
#define GDDC_PAGE_OPTION_KEY_TONE									 			1//蜂鸣器声光同步												
#define GDDC_PAGE_OPTION_KEY_BEEM_VOLUME_ADD						2//蜂鸣器音量加
#define GDDC_PAGE_OPTION_KEY_BEEM_VOLUME_DEC						3//蜂鸣器音量减
#define GDDC_PAGE_OPTION_KEY_LCD_BRG_ADD								4//液晶屏亮度增加
#define GDDC_PAGE_OPTION_KEY_LCD_BRG_DEC								5//液晶屏亮度减少
#define GDDC_PAGE_OPTION_KEY_ENTER_OK										6//返回待机页面
#define GDDC_PAGE_OPTION_KEY_ENTER_INFORMATION					7//进入信息菜单
#define GDDC_PAGE_OPTION_KEY_HAND_SWITCH_ON							8//
#define GDDC_PAGE_OPTION_KEY_ENTER_ENGINEER							9//进入工程师模式。
#define GDDC_PAGE_OPTION_TEXTDISPLAY_BEEM_VOLUME				10
#define GDDC_PAGE_OPTION_TEXTDISPLAY_LCD_BRG						11
#define GDDC_PAGE_OPTION_PROGRESS_BEEM_VOLUME						12//蜂鸣器音量调节
#define GDDC_PAGE_OPTION_PROGRESS_LCD_BRG								13//屏幕亮度调节
#define GDDC_PAGE_OPTION_KEY_RESTORE										14//恢复默认设置
/*****************************************************************************/
//方案页面
#define GDDC_PAGE_SCHEME_KEY_RENAME											1//更名按键
#define GDDC_PAGE_SCHEME_KEY_OK													2//确定
#define GDDC_PAGE_SCHEME_KEY_CANCEL											3//取消
#define GDDC_PAGE_SCHEME_KEY_SELECT_0										4	
#define GDDC_PAGE_SCHEME_KEY_SELECT_1										5
#define GDDC_PAGE_SCHEME_KEY_SELECT_2										6
#define GDDC_PAGE_SCHEME_KEY_SELECT_3										7
#define GDDC_PAGE_SCHEME_KEY_SELECT_4										8
#define GDDC_PAGE_SCHEME_KEY_SELECT_5										9
#define GDDC_PAGE_SCHEME_KEY_SELECT_6										10
#define GDDC_PAGE_SCHEME_KEY_SELECT_7										11
#define GDDC_PAGE_SCHEME_KEY_SELECT_8										12
#define GDDC_PAGE_SCHEME_KEY_SELECT_9										13
#define GDDC_PAGE_SCHEME_KEY_SELECT_10									14
#define GDDC_PAGE_SCHEME_KEY_SELECT_11									15
#define GDDC_PAGE_SCHEME_KEY_SELECT_12									16
#define GDDC_PAGE_SCHEME_KEY_SELECT_13									17
#define GDDC_PAGE_SCHEME_KEY_SELECT_14									18
#define GDDC_PAGE_SCHEME_KEY_SELECT_15									19
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_0						20
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_1						21
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_2						22
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_3						23
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_4						24
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_5						25
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_6						26
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_7						27
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_8						28
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_9						29
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_10					30
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_11					31
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_12					32
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_13					33
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_14					34
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_SCHEME_15					35
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_DETAIL0						36
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_DETAIL1						37
#define GDDC_PAGE_SCHEME_KEY_LAST_PAGE									39
#define GDDC_PAGE_SCHEME_KEY_NEXT_PAGE									40
#define GDDC_PAGE_SCHEME_TEXT_SHOWPAGE									41
#define GDDC_PAGE_SCHEME_TEXTDISPLAY_MESSAGE						42
/*****************************************************************************/
#define GDDC_PAGE_INFO_KEY_ENTER_OK											1
#define GDDC_PAGE_INFO_TEXTDISPLAY_TPYE									2
#define GDDC_PAGE_INFO_TEXTDISPLAY_SN										3
#define GDDC_PAGE_INFO_TEXTDISPLAY_LASER_WAVELENGTH			4
#define GDDC_PAGE_INFO_TEXTDISPLAY_MAX_LASER_POWER			5
#define GDDC_PAGE_INFO_TEXTDISPLAY_VERSION							6
#define GDDC_PAGE_INFO_TEXTDISPLAY_MANUFACTURE_DATE			7
#define GDDC_PAGE_INFO_TEXTDISPLAY_UUID									8
/*****************************************************************************/
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO0						1
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO1						2
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO2						3
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_INFO3						4
//通道0 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P1				100
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P2				101
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P3				102
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P4				103
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P5				104
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P6				105
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P7				106
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P8				107
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_0P9				108
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR0_1P0				109
//通道1 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P1				110
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P2				111
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P3				112
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P4				113
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P5				114
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P6				115
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P7				116
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P8				117
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_0P9				118
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR1_1P0				119
//通道2 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P1				120
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P2				121
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P3				122
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P4				123
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P5				124
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P6				125
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P7				126
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P8				127
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_0P9				128
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR2_1P0				129
//通道3 功率校正表
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P1				130
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P2				131
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P3				132
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P4				133
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P5				134
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P6				135
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P7				136
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P8				137
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_0P9				138
#define GDDC_PAGE_DISGNOSIS_TEXTDISPLAY_PWR3_1P0				139
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_YEAR						140
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_MONTH						141
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_DAY							142
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_SN							143
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_RED_LED_DC			144
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_GREEN_LED_DC		145
#define GDDC_PAGE_DIAGNOSIS_TEXTDISPLAY_BLUE_LED_DC			146
//
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_TEMPERATURE			300//屏蔽温度检测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_FIBER_PROBE			301//屏蔽光纤探测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_RFID						302//屏蔽RFID
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_ESTOP						303//屏蔽急停检测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_FOOTSWITCH			304//屏蔽脚踏检测
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_INTERLOCK				305//屏蔽安全连锁
#define GDDC_PAGE_DISGNOSIS_KEY_DISABLE_FAN_CONTRAL			306//屏蔽风扇
#define GDDC_PAGE_DISGNOSIS_KEY_CALIBRATION_MODE				307//切换正常和校正模式
#define GDDC_PAGE_DISGNOSIS_KEY_SAVE_EPROM							308//储存参数到 ERPOM 
#define GDDC_PAGE_DISGNOSIS_KEY_CLEAR_EPROM							309//恢复默认参数 EPROM						
#define GDDC_PAGE_DISGNOSIS_KEY_SERIALNUMBER						310//序列号输入
#define GDDC_PAGE_DIAGNOSIS_KEY_ENTER_OK								99
/*****************************************************************************/
#define GDDC_PAGE_RENAME_TEXTDISPLAY_NEWNAME						1
#define GDDC_PAGE_RENAME_KEY_ENTER											2
#define GDDC_PAGE_RENAME_KEY_EXIT												3
/*****************************************************************************/
#endif



