#include "sPlc.h"
#include "usbh_core.h"
/*****************************************************************************/
static int16_t FanSpeed = -1;
/*****************************************************************************/
void softDelayMs(uint16_t ms){//软件延时
	uint32_t i;
	for(i = 0;i < 1000;i ++){
		__nop();__nop();__nop();__nop();__nop();__nop();__nop();__nop();__nop();__nop();
	}
}
void UsbGpioReset(void){//模拟USB拔插动作并关闭VBUS供电
	GPIO_InitTypeDef GPIO_InitStruct;
	/* GPIO Ports Clock Enable */
	__HAL_RCC_GPIOA_CLK_ENABLE();
	/*Configure GPIO pin Output Level */
	HAL_GPIO_WritePin(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin, GPIO_PIN_RESET);
	/*Configure GPIO pin : PA12 */
	GPIO_InitStruct.Pin = USB_OTG_FS_DP_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLDOWN;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(USB_OTG_FS_DP_GPIO_Port, &GPIO_InitStruct);
	HAL_GPIO_WritePin(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin, GPIO_PIN_RESET);                                            
	softDelayMs(100);
	//先把PA12拉低再拉高，利用D+模拟USB的拔插动作   
	HAL_GPIO_WritePin(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin, GPIO_PIN_SET);
	softDelayMs(100);
	HAL_GPIO_DeInit(USB_OTG_FS_DP_GPIO_Port, USB_OTG_FS_DP_Pin);
	__HAL_RCC_GPIOA_CLK_DISABLE();
	__HAL_RCC_GPIOB_CLK_ENABLE();
	
	GPIO_InitStruct.Pin = USB_OTG_FS_ON_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_InitStruct.Pull = GPIO_PULLDOWN;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(USB_OTG_FS_ON_GPIO_Port, &GPIO_InitStruct);
	HAL_GPIO_WritePin(USB_OTG_FS_ON_GPIO_Port, USB_OTG_FS_ON_Pin, GPIO_PIN_RESET);
	softDelayMs(200);
	HAL_GPIO_DeInit(USB_OTG_FS_ON_GPIO_Port, USB_OTG_FS_ON_Pin);
	
	__HAL_RCC_GPIOG_CLK_DISABLE();	
	__HAL_RCC_USB_OTG_FS_CLK_DISABLE();//关闭USB时钟
	HAL_NVIC_DisableIRQ(OTG_FS_IRQn);//关闭USB 中断
	HAL_NVIC_ClearPendingIRQ(OTG_FS_IRQn);//清楚 USB 中断标志
}
void SystemClock_Reset(void){//复位系统时钟
	RCC_OscInitTypeDef RCC_OscInitStruct = {0};
	RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
	__HAL_RCC_BACKUPRESET_RELEASE();
	__HAL_RCC_BACKUPRESET_FORCE();
	__HAL_RCC_PLL_DISABLE();
	__HAL_RCC_HSI_DISABLE();
	/** Configure the main internal regulator output voltage */
	__HAL_RCC_PWR_CLK_DISABLE();
	__HAL_RCC_PWR_CLK_ENABLE();
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
	/** Initializes the CPU, AHB and APB busses clocks */
	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
	RCC_OscInitStruct.HSIState = RCC_HSI_ON;
	RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;
	if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK){
		Error_Handler();
	}
	/** Initializes the CPU, AHB and APB busses clocks */
	RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
	RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
	RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
	RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
	if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK){
		Error_Handler();
	}
}
void resetInit(void){//复位后初始化
	HAL_DeInit();
	HAL_CRC_MspDeInit(&hcrc);
	HAL_RNG_MspDeInit(&hrng);
	
	HAL_TIM_Base_MspDeInit(&htim2);
	HAL_TIM_Base_MspDeInit(&htim3);
	HAL_TIM_Base_MspDeInit(&htim4);
	HAL_TIM_Base_MspDeInit(&htim5);
	HAL_TIM_Base_MspDeInit(&htim8);
	HAL_TIM_Base_MspDeInit(&htim10);
	HAL_TIM_Base_MspDeInit(&htim13);
	HAL_TIM_Base_MspDeInit(&htim14);
	
	HAL_I2C_MspDeInit(&hi2c2);
	HAL_UART_MspDeInit(&huart1);
	HAL_UART_MspDeInit(&huart4);
	HAL_UART_MspDeInit(&huart5);
	HAL_ADC_MspDeInit(&hadc1);
	HAL_DAC_MspInit(&hdac);
	
	USBH_DeInit(&hUsbHostFS);
	//复位RCC时钟
	SystemClock_Reset();
	UsbGpioReset();
	__enable_irq();
}
void delayMs(uint32_t delayMs){//SPLC 阻塞延时
	vTaskDelay(delayMs);
}
void setFanSpeed(int16_t speed){//设置风扇转速
	if(FanSpeed != speed){
		if(speed > CONFIG_FAN_MAX_DC){
			speed = CONFIG_FAN_MAX_DC;
		}
		if(speed < CONFIG_FAN_MIN_DC){
			speed = CONFIG_FAN_MIN_DC;
		}
		speed = 50 * speed;
		SET_FAN_PWM_DC(speed);
		if(speed != 0){
			SET_FAN_PWM_ON;//打开TIM
		}
		else{
			SET_FAN_PWM_OFF;//关闭TIM
		}
		FanSpeed = speed;
		printf("%s,%d,%s:set fan:%d\n",__FILE__, __LINE__, __func__, speed);	
	}
}

void morseCodeDiag(uint8_t diag){//蜂鸣器诊断声音 摩尔斯电码
	//关闭USB VBUS
	switch(diag){
		case '0':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case '1':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		};
		case '2':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		};
		case '3':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case '4':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case '5':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '6':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '7':{	
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '8':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case '9':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'A':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'B':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;			
		}
		case 'C':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'D':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'E':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'F':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'G':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'H':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;			
		}
		case 'I':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'J':{
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'K':{
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'L':{//．━ ．．
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//.
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_SHORT_TIME);SET_RED_LED_OFF;
			break;
		}
		case 'M':{//━ ━
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;vTaskDelay(CONFIG_MORSECODE_SPACE_TIME);
			//-
			SET_RED_LED_ON;vTaskDelay(CONFIG_MORSECODE_LONG_TIME);SET_RED_LED_OFF;
			break;
		}
		default:break;
	}
	vTaskDelay(3000);
}

uint32_t getOriginBootloadCrc(void){//计算MCU Bootload CRC32
	uint8_t val;
	uint32_t i;
	uint32_t crc32;
	crc32Clear();
	for(i = BOOTLOADER_FLASH_START_ADDRESS;i < BOOTLOADER_FLASH_END_ADDRESS;i ++){
		val = *(__IO uint8_t*)(i);
		crc32 = crc32CalculateAdd(val);//CRC32计算连续字节
	}
	return crc32;	
}
uint32_t getOriginAppCrc(void){//计算MCU APP CRC32
	uint8_t val;
	uint32_t i;
	uint32_t crc32;
	crc32Clear();
	for(i = APPLICATION_FLASH_START_ADDRESS;i < APPLICATION_FLASH_END_ADDRESS;i ++){
		val = *(__IO uint8_t*)(i);
		crc32 = crc32CalculateAdd(val);//CRC32计算连续字节
	}
	return crc32;	
}




